Add check for potion type
promcteam/proskillapi pull request #516
Opened 2023-08-01 16:48 UTC by fructozer

as the title says

2023-08-01 16:53 UTC, Travja requested changes

2023-08-01 16:53 UTC, Travja commented on src/main/java/com/sucy/skill/dynamic/trigger/ConsumeTrigger.java
> +            if (!settings.getString("potion", "Any").replace(" ","_").equalsIgnoreCase(type)) return false;
This will fail if the potion is put in as 'Any'. Any will never equal the used potion type and will always return false.

2023-08-01 16:53 UTC, Travja commented on src/main/java/com/sucy/skill/dynamic/trigger/ConsumeTrigger.java
> +            if (!settings.getString("potion", "Any").replace(" ","_").equalsIgnoreCase(type)) return false;
This will fail if the potion is put in as 'Any'. Any will never equal the used potion type and will always return false.

2023-08-01 16:55 UTC, Travja commented on src/main/java/com/sucy/skill/dynamic/trigger/ConsumeTrigger.java
> +        if (item_name.equalsIgnoreCase("potion") && req.equalsIgnoreCase(item_name)){
This also doesn't account for splash/lingering potions. Perhaps using `item_name.contains` would work instead.

2023-08-01 17:02 UTC, Travja commented on src/main/java/com/sucy/skill/dynamic/trigger/ConsumeTrigger.java
> +        if (item_name.equalsIgnoreCase("potion") && req.equalsIgnoreCase(item_name)){
Oh. Haha I guess you're right. Lol. My bad 🤣

2023-08-01 17:08 UTC, Travja approved these changes

2023-08-02 06:59 UTC, fructozer commented
Add Loaded command 
describe: list loaded content eg group, class, skill and attribute
usage: <sub>/class loaded <group|class|skill|attr></sub>
Add Heal trigger 
#502

2023-08-02 07:01 UTC, fructozer commented
Tested on paper 1.20 for both

2023-08-02 16:40 UTC, Travja commented
Would it be possible to split the consume trigger, loaded command, and heal trigger into separate PRs?

2023-08-02 17:07 UTC, fructozer commented
> Would it be possible to split the consume trigger, loaded command, and heal trigger into separate PRs?

Well, It's automated so I can't separate them

2023-08-02 17:08 UTC, Travja commented
> Well, It's automated so I can't separate them

It would be a matter of creating separate branches on your fork and creating different PRs to merge from those branches to dev here.

2023-08-02 17:11 UTC, fructozer commented
Oke I got it, I'll do it next time.

2023-08-03 00:33 UTC, closed without merging