ChatTrigger implemented
promcteam/proskillapi pull request #534
Opened 2023-09-07 10:05 UTC by neYaANK

2023-09-07 13:40 UTC, Travja requested changes

2023-09-07 13:40 UTC, Travja commented on src/main/java/com/sucy/skill/dynamic/trigger/ChatTrigger.java
> +        String      message         = settings.getString("message", "");
We should also add an option here to match with regex instead of just a `contains`

2023-09-07 17:37 UTC, Travja approved these changes
Awesome! Looks good! Could you get a PR set up for the editor and link it here too?

2023-09-08 09:41 UTC, neYaANK commented
Here's the link to editor PR
https://github.com/Travja/editor/pull/170

2023-09-08 13:20 UTC, merged