Add persistent value
promcteam/proskillapi pull request #558
Opened 2023-10-07 06:38 UTC by fructozer

Add "ValueLoadMechanic" to load value from persistent data to cast data
Add "Save" option to all Value mechanic to save result value to persistent data of current account

2023-10-07 11:02 UTC, Travja requested changes
Just a couple of things to look at. Other than that, great work!

2023-10-07 11:30 UTC, fructozer commented on src/main/java/com/sucy/skill/api/player/PlayerData.java
> +     *
As you can see, I was going to write something but didn't write anything there. 
The problem is that the function name says it all. 
And I finally forgot about it, thanks for the reminder.

2023-10-07 11:32 UTC, fructozer commented on src/main/java/com/sucy/skill/dynamic/mechanic/ValueLoadMechanic.java
> +            SkillAPI.getPlayerData((OfflinePlayer) caster).setPersistentData(key,data.get(key));
The answer is yes. Because it can be replaced by an existing value when override option is false.

2023-10-14 02:37 UTC, Travja approved these changes

2023-10-14 02:48 UTC, merged